//Title: proj2.cpp
//Author: Jeremy Dixon
//Date: 2/25/2025
//Description: This is part of the DoodleGod Project in CMSC 202 @ UMBC

//Do not edit this file

#include "Game.h"

#include <iostream>
#include <cstdlib>
#include <string>
using namespace std;

int main () {
  Game newGame; //Creates a new game object
  newGame.StartGame(); //Calls start game on game object
  return 0;
}
